//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumno1.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService3Soap")]
    public interface WebService3Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] AgregarAlumno(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAlumnoAsync(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAlumnos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarAlumnos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAlumnos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAlumnosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ActualizarAlumno(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAlumnoAsync(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] EliminarAlumno(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAlumnoAsync(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BuscarAlumno(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAlumnoAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService3SoapChannel : Alumno1.ServiceReference1.WebService3Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService3SoapClient : System.ServiceModel.ClientBase<Alumno1.ServiceReference1.WebService3Soap>, Alumno1.ServiceReference1.WebService3Soap {
        
        public WebService3SoapClient() {
        }
        
        public WebService3SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService3SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] AgregarAlumno(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela) {
            return base.Channel.AgregarAlumno(codAlumno, Apellidos, Nombres, LugarNac, FechaNac, codEscuela);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAlumnoAsync(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela) {
            return base.Channel.AgregarAlumnoAsync(codAlumno, Apellidos, Nombres, LugarNac, FechaNac, codEscuela);
        }
        
        public System.Data.DataSet ListarAlumnos() {
            return base.Channel.ListarAlumnos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAlumnosAsync() {
            return base.Channel.ListarAlumnosAsync();
        }
        
        public string[] ActualizarAlumno(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela) {
            return base.Channel.ActualizarAlumno(codAlumno, Apellidos, Nombres, LugarNac, FechaNac, codEscuela);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAlumnoAsync(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela) {
            return base.Channel.ActualizarAlumnoAsync(codAlumno, Apellidos, Nombres, LugarNac, FechaNac, codEscuela);
        }
        
        public string[] EliminarAlumno(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela) {
            return base.Channel.EliminarAlumno(codAlumno, Apellidos, Nombres, LugarNac, FechaNac, codEscuela);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAlumnoAsync(string codAlumno, string Apellidos, string Nombres, string LugarNac, System.DateTime FechaNac, string codEscuela) {
            return base.Channel.EliminarAlumnoAsync(codAlumno, Apellidos, Nombres, LugarNac, FechaNac, codEscuela);
        }
        
        public System.Data.DataSet BuscarAlumno(string texto, string criterio) {
            return base.Channel.BuscarAlumno(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAlumnoAsync(string texto, string criterio) {
            return base.Channel.BuscarAlumnoAsync(texto, criterio);
        }
    }
}
